print("Welcome to the Magic Reverser Thingy!\n")
user_input = input("Please enter a word or phrase that you would like to reverse: ")
print()
print("working.... beep boop\n........Ta-da!\n")
print(f"Here it is: {user_input[::-1].title()}\n")
print("Insert your coin to try again.")
